pipeline:
  name: Python_new_build
  identifier: Python_new_build
  projectIdentifier: harnessdeployment
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: python_build_connector
        build: <+input>
  stages:
    - stage:
        name: Python_new_build
        identifier: Python_new_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: Git Clone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: python_build_connector
                    build:
                      type: branch
                      spec:
                        branch: main
